version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
      - ./docker/logs/php:/var/log/php
      - ./docker/logs/php-fpm:/var/log/php-fpm
    environment:
      PHP_FPM_ERRLOG: /var/log/php-fpm/php-fpm.log
      PHP_ERROR_LOG: /var/log/php/php_errors.log
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/logs/nginx:/var/log/nginx
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: laravel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: support_feb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./support_feb.sql:/docker-entrypoint-initdb.d/support_feb.sql
      - ./docker/logs/postgresql:/var/log/postgresql
    command:
      - "postgres"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=/var/log/postgresql"
      - "-c"
      - "log_filename=postgresql-%Y-%m-%d_%H%M%S.log"
      - "-c"
      - "log_statement=all"
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
