version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html/support
    volumes:
      - ./logs/laravel:/var/www/html/storage/logs
      - .:/var/www/html/support
    depends_on:
      - db
    networks:
      - laravel_network

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: support
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./logs/postgres:/var/log/postgresql
      - postgres_data:/var/lib/postgresql/data
      - ./support_mod.sql:/docker-entrypoint-initdb.d/support_mod.sql
    ports:
      - "5433:5432"
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - .:/var/www/html/support
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

volumes:
  postgres_data:

networks:
  laravel_network:
